from utils.device import get_device

DEVICE = get_device()
SEED = 42

LOG_DIR = "logs/"
RESULTS_DIR = "results/"

INPUT_DIM = 20
NUM_CLASSES = 2
STREAM_CHUNK_SIZE = 128
STREAM_TOTAL_SAMPLES = 30000

DRIFT_DELTA = 0.99
DRIFT_DELTA_TEST = 0.1
DRIFT_MIN_VOTES = 1

MLP_HIDDEN_DIM = 128
LR = 5e-4
WEIGHT_DECAY = 5e-6

REPLAY_BUFFER_SIZE = 500
REPLAY_BATCH_SIZE = 128
REPLAY_AFTER_DRIFT_STEPS = 25

EWC_LAMBDA = 20000.0
EWC_FISHER_SAMPLES = 300
EWC_FISHER_BATCH = 64

DEBUG_DRIFT = False
